[project]
name = "data-deficient-plant-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.3.3",
    "pygbif>=0.6.6",
    "requests>=2.32.5",
]
